server:
  port: 8089

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  http:
    encoding:
      force: true
      charset: utf-8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.170.191/test?serverTimezone=UTC
    username: root
    password: qwe123

snow:
  data-center: 1
  worker: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo07.model